version: '3'

services:
  aistudio-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2048:2048"
    volumes:
      - ./auth_profiles:/app/auth_profiles
      - ./logs:/app/logs
      - ./errors_py:/app/errors_py
    environment:
      # 基础配置
      - SERVER_LOG_LEVEL=INFO
      - LAUNCH_MODE=direct_debug_no_browser
      - SERVER_REDIRECT_PRINT=false
      # 新增的环境变量支持
      - DEBUG_LOGS_ENABLED=false
      - TRACE_LOGS_ENABLED=false
      # 代理设置 (可选，根据需要取消注释)
      # - HTTPS_PROXY=http://your-proxy:port
      # - HTTP_PROXY=http://your-proxy:port
      # - NO_PROXY=localhost,127.0.0.1
      # 认证相关设置
      - AUTO_SAVE_AUTH=false
      - AUTH_SAVE_TIMEOUT=30
    restart: unless-stopped
    user: root  # 保留 root 用户以避免权限问题
